[package]
name = "jog"
version = "0.1.8"
edition = "2024"
license = "MIT"
description = "A small terminal UI for browsing and triggering GitHub Actions workflows."
readme = "README.md"

[dependencies]
ratatui = "0.29"
crossterm = { version = "0.28", features = ["event-stream"] }
tokio = { version = "1", features = ["full"] }
tokio-util = { version = "0.7", features = ["io"] }
octocrab = "0.44"
clap = { version = "4", features = ["derive"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
serde_yml = "0.0.12"
toml = "0.9"
async-trait = "0.1"
anyhow = "1"
futures = "0.3"
chrono = { version = "0.4", features = ["serde"] }
dirs = "5"
open = "5"


[profile.release]
opt-level = "z"      # or "s" (z = smallest)
lto = true           # link-time optimization
codegen-units = 1    # better optimization, smaller binary
panic = "abort"      # removes unwinding machinery
strip = true         # strips symbols (since Rust 1.70+)
